version: '3'

services:
  primary:
    image: 'amd64/postgres'
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./primary.conf:/etc/postgresql/postgresql.conf
      - ./primary_hba.conf:/etc/postgresql/pg_hba.conf
    entrypoint:
      - docker-entrypoint.sh
      - -c
      - 'config_file=/etc/postgresql/postgresql.conf'
      - -c
      - 'hba_file=/etc/postgresql/pg_hba.conf'
  standby:
    image: 'amd64/postgres'
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./standby.conf:/etc/postgresql/postgresql.conf
    entrypoint:
      - docker-entrypoint.sh
      - -c
      - 'config_file=/etc/postgresql/postgresql.conf'